// swift-tools-version:6.0
import PackageDescription
import Foundation

// MARK: - Plozz modular package
//
// Plozz is split into small, single-responsibility modules so that:
//  * pure logic (models, networking, discovery, session) is unit-testable in
//    isolation, without a running tvOS UI;
//  * a second provider (Plex, Phase 2) can be dropped in behind `MediaProvider`
//    without touching feature code;
//  * build times stay low and ownership boundaries stay clear.
//
// The platform application targets live in `App/` and are generated by
// XcodeGen (see `project.yml`); they link their platform-specific shells below.
let package = Package(
    name: "Plozz",
    platforms: [
        .iOS(.v18),
        .tvOS(.v18)
    ],
    products: [
        .library(name: "CoreModels", targets: ["CoreModels"]),
        .library(name: "CoreNetworking", targets: ["CoreNetworking"]),
        .library(name: "CoreUI", targets: ["CoreUI"]),
        .library(name: "MetadataKit", targets: ["MetadataKit"]),
        .library(name: "FeatureDiscoveryCore", targets: ["FeatureDiscoveryCore"]),
        .library(name: "FeatureDiscovery", targets: ["FeatureDiscovery"]),
        .library(name: "ProviderJellyfin", targets: ["ProviderJellyfin"]),
        .library(name: "ProviderPlex", targets: ["ProviderPlex"]),
        .library(name: "ProviderShare", targets: ["ProviderShare"]),
        .library(name: "ProviderTrailers", targets: ["ProviderTrailers"]),
        .library(name: "RatingsService", targets: ["RatingsService"]),
        .library(name: "TraktService", targets: ["TraktService"]),
        .library(name: "SeerService", targets: ["SeerService"]),
        .library(name: "SimklService", targets: ["SimklService"]),        .library(name: "AniListService", targets: ["AniListService"]),
        .library(name: "MALService", targets: ["MALService"]),
        .library(name: "LastFmService", targets: ["LastFmService"]),
        .library(name: "FeatureAuthCore", targets: ["FeatureAuthCore"]),
        .library(name: "FeatureAuth", targets: ["FeatureAuth"]),
        .library(name: "FeatureHomeCore", targets: ["FeatureHomeCore"]),
        .library(name: "FeatureHome", targets: ["FeatureHome"]),
        .library(name: "FeatureSearchCore", targets: ["FeatureSearchCore"]),
        .library(name: "FeaturePlayback", targets: ["FeaturePlayback"]),
        .library(name: "FeatureSearch", targets: ["FeatureSearch"]),
        .library(name: "FeatureSettings", targets: ["FeatureSettings"]),
        .library(name: "FeatureProfiles", targets: ["FeatureProfiles"]),
        .library(name: "FeatureSyncSetup", targets: ["FeatureSyncSetup"]),
        .library(name: "FeatureMusic", targets: ["FeatureMusic"]),
        .library(name: "TopShelfKit", targets: ["TopShelfKit"]),
        .library(name: "CrashReporting", targets: ["CrashReporting"]),
        .library(name: "MediaDownloads", targets: ["MediaDownloads"]),
        .library(name: "MediaTransportCore", targets: ["MediaTransportCore"]),
        .library(name: "MediaTransportHTTP", targets: ["MediaTransportHTTP"]),
        .library(name: "MediaTransportSMB", targets: ["MediaTransportSMB"]),
        .library(name: "MediaTransportWebDAV", targets: ["MediaTransportWebDAV"]),
        .library(name: "MediaTransportSFTP", targets: ["MediaTransportSFTP"]),
        .library(name: "TransportNFS", targets: ["TransportNFS"]),
        .library(name: "MediaTransportNFS", targets: ["MediaTransportNFS"]),
        .library(name: "AppRuntime", targets: ["AppRuntime"]),
        .library(name: "AppShell", targets: ["AppShell"]),
        .library(name: "AppShelliOS", targets: ["AppShelliOS"])
    ],
    dependencies: [
        // Pure-Swift, dependency-free YouTube stream extractor. Backs online
        // trailer playback: TMDb hands us a YouTube video id, YouTubeKit resolves
        // a natively-playable progressive stream URL we feed straight to AVPlayer
        // (the same approach Infuse uses). It includes an optional remote fallback
        // so extraction keeps working when YouTube changes its internal API.
        .package(url: "https://github.com/alexeichhorn/YouTubeKit.git", from: "0.4.8"),

        // AetherEngine — production media player engine for Apple platforms.
        // FFmpeg demuxes, VideoToolbox decodes, AVPlayer handles Dolby Atmos.
        // Powers the native HLS-fMP4 remux path for MKV → DoVi + Atmos + seek.
        // See AGENTS.local.md › "Playback engine (AetherEngine / Plozzigen)".
        //
        // Pinned by exact commit to the annotated tag
        //   `plozz-pin-5.20.6-seekfixes-atmos` → 1a0e81bfbed667f1a51154397d2fdfee27b1bce5
        // on the thatcube fork. The tag keeps this commit permanently reachable
        // (a bare branch SHA could be force-pushed away; a tagged one cannot), so
        // pinning the SHA here is both immutable and human-traceable. The tagged
        // stack, on the upstream 5.20.6 base, bundles:
        //   64a3f16 opt-in bounded E-AC-3 JOC/Atmos decode-detection probe
        //   2feb7d2 progress-aware deadline extend (don't tear down a slow-but-serving producer)
        //   0c42bb5 recovery hold-at-target (never revert the clock to the old position)
        //   1f35669 forward-overshoot landing (a seek that lands past target is done, not re-sought)
        //   08c3ee3 edge-triggered finalize (clear the loading state the instant playback resumes)
        //   1a0e81b deactivate AVAudioSession on final teardown (stops looping Atmos passthrough on exit)
        //
        // The previous stack's `b441b5a` (re-anchor the producer when a forward-seek
        // target is unbuffered) was DROPPED here because upstream implemented the same
        // fix independently as AE#141: `shouldReanchorProducerAfterSeekDeadline` now
        // gates on `targetBeyondProducerCoverage` (real producer coverage) instead of
        // our `bufferedEnd` heuristic, which is the stronger signal. The dependent
        // patches above were rewired onto the upstream gate during the rebase.
        //
        // SMB enters AetherEngine only through Plozz's protocol-neutral custom-source
        // bridge; the engine's legacy SMB URL product is not linked.
        .package(url: "https://github.com/thatcube/AetherEngine", revision: "1a0e81bfbed667f1a51154397d2fdfee27b1bce5"),
        // NOTE: FFmpegBuild (FFmpeg n8.1.x decode-only) and LibDovi (Dolby Vision
        // RPU parser) are pulled in TRANSITIVELY by AetherEngine — its own manifest
        // declares and consumes them. Plozz used to declare them directly only for
        // the retired hybrid-engine target; no Plozz target references
        // their products, so the direct declarations were removed (SwiftPM flagged
        // them as unused). AetherEngine owns their version alignment.

        // Sentry (getsentry/sentry-cocoa) — powers the OPT-IN, off-by-default
        // crash reporter (Settings ▸ Help & Diagnostics ▸ Share Crash Reports).
        // Prebuilt binary xcframework (no build-time compilation of the SDK).
        // Nothing is sent unless the user opts in AND a DSN was baked into the
        // build; see the `CrashReporting` target for the privacy-hardened config.
        .package(url: "https://github.com/getsentry/sentry-cocoa", from: "9.19.0"),

        // SMBClient — pure-Swift, MIT SMB client over NWConnection. Declared here
        // for the isolated **MediaTransportSMB** adapter and ProviderShare's
        // pre-save discovery/share enumeration. Browsing and scanning consume the
        // protocol-neutral MediaTransportCore contracts. AetherEngine already pulls
        // SMBClient transitively and owns the playback byte-reads (SMBConnection);
        // SwiftPM unifies both onto one version.
        //
        // Pinned to thatcube/SMBClient@smb3, our fork that adds SMB 3.x + 3.1.1
        // GCM encryption and Session.isGuestSession (see the guest/credential
        // handling in ProviderShare/SMBDiscovery). This root-level reference
        // overrides the same-identity ("smbclient") reference AetherEngine pulls
        // transitively, so BOTH browse and playback use the SMB3 fork. Proposed
        // upstream as kishikawakatsumi/SMBClient#234; switch back to
        //   .package(url: "https://github.com/kishikawakatsumi/SMBClient", from: "0.3.1"),
        // once that lands.
        .package(url: "https://github.com/thatcube/SMBClient.git", revision: "d8baadc1a4f1287ebf1e8b4702ca38bd6e237fef"),

        // swift-nio-ssh — Apple's pure-Swift SSH protocol implementation
        // (Apache-2.0), used ONLY by the isolated **MediaTransportSFTP** adapter.
        // It declares tvOS support directly and rides Apple's own swift-nio +
        // swift-crypto (no third-party fork), so the security-critical SSH/host-key
        // layer stays on a maintained upstream. It provides the SSH transport only
        // — MediaTransportSFTP layers a thin, read-only SFTP v3 subsystem client on
        // top (INIT/REALPATH/OPENDIR/OPEN/FSTAT/READ/CLOSE) behind the neutral
        // MediaTransportCore contracts, mirroring MediaTransportSMB's shape. This is
        // the deliberate alternative to Citadel, whose main rides a stale personal
        // fork-of-a-fork of swift-nio-ssh for that same credential/host-key path.
        .package(url: "https://github.com/apple/swift-nio-ssh.git", from: "0.11.0"),

        // swift-nio — declared directly so MediaTransportSFTP can import the NIO
        // core products (NIOCore/NIOPosix/NIOFoundationCompat/NIOConcurrencyHelpers)
        // it needs to drive swift-nio-ssh's channels. Already resolved transitively
        // via swift-nio-ssh; SwiftPM unifies the version.
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.81.0"),

        // swift-crypto — declared directly for MediaTransportSFTP's SSH host-key
        // SHA-256 fingerprinting (and, in tests, ed25519 key material for the
        // pin). Apple-maintained, tvOS-supported, already resolved transitively
        // via swift-nio-ssh; SwiftPM unifies the version.
        .package(url: "https://github.com/apple/swift-crypto.git", "3.0.0" ..< "5.0.0"),
    ],
    targets: [
        // MARK: Core
        .target(
            name: "CoreModels",
            swiftSettings: [
                .define("PLOZZ_DIAGNOSTICS", .when(configuration: .debug))
            ]
        ),
        .target(
            name: "CoreNetworking",
            dependencies: ["CoreModels"]
        ),

        // MARK: Shared UI (design system + reusable tvOS components)
        .target(
            name: "CoreUI",
            dependencies: ["CoreModels", "MetadataKit"],
            resources: [.process("Resources")]
        ),

        // MARK: Scalable external metadata/artwork (content-type-routed providers)
        //
        // Foundation-only so it stays unit-testable off-device. Houses the keyless,
        // per-IP artwork providers (AniList, Kitsu, TVmaze, Deezer, MusicBrainz),
        // the optional proxy/token-gated TMDb provider, the content-type classifier
        // + ArtworkRouter that picks the right provider chain, and a persistent
        // resolved-URL disk cache. This is the engine behind goals 1–5 scaling to
        // a large user base without a "bring your own API key" design.
        .target(
            name: "MetadataKit",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),

        // MARK: Providers
        .target(
            name: "ProviderJellyfin",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "ProviderPlex",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        // Second-class local media-share backend (SMB today). Scans a share into
        // a synthesised library and conforms to `MediaProvider` so the rest of the
        // app treats it like Plex/Jellyfin. Runtime browsing/scanning use injected
        // MediaTransportCore sessions; SMBClient remains here only for setup-time
        // SMB discovery/share enumeration. Playback still flows through
        // EnginePlozzigen's existing SMB path. See docs/media-share-proposal.md.
        .target(
            name: "ProviderShare",
            dependencies: [
                "CoreModels",
                "CoreNetworking",
                "MediaTransportCore",
                "MetadataKit",
                .product(name: "SMBClient", package: "SMBClient"),
            ]
        ),
        // Synthetic provider for online (TMDb → YouTube) trailers. Conforms to
        // `MediaProvider` so a trailer can be played by the existing player; only
        // `playbackInfo(for:)` does real work (YouTubeKit stream extraction), the
        // rest are inert stubs. Kept in its own leaf module so YouTubeKit stays
        // out of every other target's link graph.
        .target(
            name: "ProviderTrailers",
            dependencies: [
                "CoreModels",
                .product(name: "YouTubeKit", package: "YouTubeKit")
            ]
        ),
        .target(
            name: "RatingsService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "TraktService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "SeerService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "SimklService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "AniListService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "MALService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "LastFmService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),

        // MARK: Features
        .target(
            name: "FeatureDiscoveryCore",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "FeatureDiscovery",
            dependencies: ["CoreModels", "CoreUI", "FeatureDiscoveryCore"]
        ),
        .target(
            name: "FeatureAuthCore",
            dependencies: ["CoreModels", "CoreNetworking", "ProviderJellyfin", "ProviderPlex"]
        ),
        .target(
            name: "FeatureAuth",
            dependencies: ["CoreModels", "CoreUI", "FeatureAuthCore", "ProviderPlex"]
        ),
        .target(
            name: "FeatureHomeCore",
            dependencies: [
                "CoreModels",
                "CoreNetworking",
                "MetadataKit",
                "RatingsService",
                "ProviderTrailers"
            ]
        ),
        .target(
            name: "HeroUI",
            dependencies: ["CoreModels", "CoreUI", "FeatureHomeCore"]
        ),
        .target(
            name: "FeatureHome",
            dependencies: ["CoreModels", "CoreNetworking", "CoreUI", "FeatureHomeCore", "HeroUI", "MetadataKit", "TopShelfKit", "RatingsService", "ProviderTrailers"]
        ),
        .target(
            name: "FeaturePlayback",
            dependencies: ["CoreModels", "CoreNetworking", "CoreUI", "TraktService", "MetadataKit"],
            linkerSettings: [
                // Force-link AVKit on tvOS so its `UIWindow (AVAdditions)`
                // category (which adds `avDisplayManager`, used to drive the
                // Dolby Vision / HDR display-mode switch) is registered at
                // runtime. Swift's autolink hint for a category-only reference
                // gets dropped through the SPM static-lib → app link, leaving the
                // selector unrecognized (instant crash) unless linked explicitly.
                .linkedFramework("AVKit", .when(platforms: [.tvOS]))
            ]
        ),
        .target(
            name: "FeatureSearchCore",
            dependencies: ["CoreModels"]
        ),
        .target(
            name: "FeatureSearch",
            dependencies: ["CoreModels", "CoreUI", "FeatureSearchCore"]
        ),
        .target(
            name: "FeatureSettings",
            dependencies: ["CoreModels", "CoreUI", "CoreNetworking", "CrashReporting", "FeatureProfiles", "TraktService", "SeerService", "SimklService", "AniListService", "MALService", "LastFmService"]
        ),
        .target(
            name: "FeatureProfiles",
            dependencies: ["CoreModels", "CoreUI"]
        ),

        // MARK: Sync & Setup (cross-device onboarding — feature-flagged, v1)
        //
        // Non-secret config sync + device pairing crypto. Depends only on
        // CoreModels; uses CryptoKit for the pairing seal (kept out of the
        // Foundation-only CoreModels). v1 carries NON-SECRET config only.
        .target(
            name: "FeatureSyncSetup",
            dependencies: ["CoreModels"]
        ),

        // MARK: Music (browse + audio playback engine)
        //
        // Self-contained music experience: aggregator/view models, the conditional
        // Music tab UI, and the app-scoped `AudioPlaybackController` (AVQueuePlayer
        // + background audio + Now Playing). Depends only on CoreModels/CoreUI so
        // it stays decoupled from the video feature modules.
        .target(
            name: "FeatureMusic",
            dependencies: ["CoreModels", "CoreUI", "MetadataKit", "CoreNetworking"]
        ),

        // MARK: Top Shelf (shared with the tvOS Top Shelf extension)
        //
        // `TopShelfSnapshot` + `TopShelfStore` are Foundation-only and are also
        // compiled directly into the Top Shelf extension by source path (see
        // project.yml). `TopShelfPublisher` imports CoreModels and is therefore
        // app-only — the extension never compiles it.
        .target(
            name: "TopShelfKit",
            dependencies: ["CoreModels"]
        ),

        // MARK: Crash reporting (opt-in, off by default)
        //
        // Wraps Sentry behind a small `CrashReporter` protocol so the rest of the
        // app never imports Sentry directly and builds without a DSN are a true
        // no-op. Reports are only ever sent when the user has opted in (Settings ▸
        // Help & Diagnostics) AND the build shipped with a `PLOZZ_SENTRY_DSN`.
        // The Sentry config here is privacy-hardened: crash + hang captures only,
        // all automatic UI/network telemetry disabled, and a hard scrub of PII in
        // `beforeSend`/`beforeBreadcrumb`. Depends only on Sentry + Foundation.
        .target(
            name: "CrashReporting",
            dependencies: [
                .product(name: "Sentry", package: "sentry-cocoa"),
            ]
        ),

        // MARK: Protocol-neutral media transport
        .target(
            name: "MediaTransportCore",
            dependencies: ["CoreModels"],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: Offline downloads (headless, shared, platform-neutral)
        //
        // The offline-download FOUNDATION: a durable, resumable, transport-agnostic
        // download registry + queue + policy that both future iOS/iPadOS apps and
        // the tvOS app inherit. Depends only on CoreModels + the protocol-neutral
        // MediaTransportCore (the cursor byte API it downloads through). No UI /
        // Feature / provider modules — arch-guard keeps it a clean lower layer.
        .target(
            name: "MediaDownloads",
            dependencies: ["CoreModels", "MediaTransportCore"]
        ),

        // MARK: WebDAV/HTTP transport
        //
        // Foundation-only WebDAV/plain-HTTP adapter primitives built on the
        // protocol-neutral MediaTransportCore: origin/redirect discipline,
        // credential preflight + password/Bearer auth policy, exact-leaf TLS
        // pinning, per-(account, credential revision, origin, trust
        // revision, role) ephemeral session isolation, bounded PROPFIND
        // parsing, and validated ranged reads. See
        // `Sources/MediaTransportHTTP/README.md` for the adapter's scope.
        //
        // NOT consumed by AppShell/the App target — this is a standalone,
        // independently-testable module, not shipping app behavior yet.
        // Strict concurrency is opted into explicitly for this target only
        // (the package as a whole stays pinned to Swift 5 language mode; see
        // `swiftLanguageModes` below) so this new surface is held to a
        // stricter bar from day one.
        .target(
            name: "MediaTransportHTTP",
            dependencies: ["CoreModels", "MediaTransportCore"],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: SMB transport
        .target(
            name: "MediaTransportSMB",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                .product(name: "SMBClient", package: "SMBClient"),
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: WebDAV transport
        //
        // Composes the MediaTransportHTTP primitives (OPTIONS/PROPFIND/range
        // reads, origin/redirect/trust discipline) into a MediaTransportCore
        // adapter, mirroring MediaTransportSMB's shape. No SMBClient/URLSession
        // logic of its own — it only wires the HTTP primitives to the
        // protocol-neutral filesystem/byte-source contracts.
        .target(
            name: "MediaTransportWebDAV",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportHTTP",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: SFTP transport
        //
        // Layers a thin, read-only SFTP v3 subsystem client on top of Apple's
        // swift-nio-ssh (SSH transport only) and composes it into a
        // MediaTransportCore adapter, mirroring MediaTransportSMB's shape (a
        // stub-testable backend seam, cursor-safe random-access byte source). No
        // SSH/crypto logic of its own — swift-nio-ssh owns key exchange, ciphers,
        // and host-key verification; this module only frames the SFTP messages we
        // need and wires them to the protocol-neutral filesystem/byte-source
        // contracts.
        .target(
            name: "MediaTransportSFTP",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                .product(name: "NIOSSH", package: "swift-nio-ssh"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOPosix", package: "swift-nio"),
                .product(name: "NIOConcurrencyHelpers", package: "swift-nio"),
                .product(name: "NIOFoundationCompat", package: "swift-nio"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: NFS transport
        //
        // `TransportNFS` is a self-contained, dependency-free pure-Swift NFSv3
        // client (XDR + ONC-RPC + portmap + MOUNT + read-only NFSv3 procedures)
        // over NWConnection — the NFS analogue of `SMBClient`, but written
        // in-house because no shippable Swift NFS library exists (libnfs is LGPL,
        // a compliance risk for a closed-source App Store app). Foundation +
        // Network only; no CoreModels/MediaTransportCore dependency so the whole
        // protocol layer is unit-testable in isolation.
        .target(
            name: "TransportNFS",
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: MediaTransportNFS adapter
        //
        // Composes the TransportNFS client into a MediaTransportCore adapter,
        // mirroring MediaTransportSMB/MediaTransportWebDAV exactly. The NFS
        // backend sits behind a protocol seam so the adapter/session/filesystem/
        // byte-source can be proven hermetically with a stubbed backend.
        .target(
            name: "MediaTransportNFS",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "TransportNFS",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: FTP/FTPS transport
        //
        // A minimal FTP protocol engine over Network.framework (NWConnection),
        // composed into the protocol-neutral MediaTransportCore adapter shape —
        // mirroring MediaTransportSMB/WebDAV. Supports plain FTP + implicit FTPS
        // (TLS from connect); explicit FTPS (AUTH TLS/StartTLS) is unavailable on
        // tvOS (Network.framework has no StartTLS) and is rejected at connect.
        // Random-access playback reads use REST (restart offset) + RETR.
        .target(
            name: "MediaTransportFTP",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),

        // MARK: AetherEngine integration (native HLS-fMP4 remux engine)
        //
        // Wraps AetherEngine (the upstream media-player library) behind Plozz's
        // `VideoEngine` protocol. AetherEngine handles: FFmpeg demux → on-device
        // copy-remux → localhost HLS-fMP4 → AVPlayer, with bounded segment cache,
        // backpressure, producer-restart seek, Dolby Vision signaling, and Atmos
        // passthrough. This module is the integration adapter — all Plozz-specific
        // orchestration (server progress, subtitles, routing) stays in
        // FeaturePlayback / PlayerViewModel.
        .target(
            name: "EnginePlozzigen",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "FeaturePlayback",
                .product(name: "AetherEngine", package: "AetherEngine"),
            ]
        ),

        .target(
            name: "AppRuntime",
            dependencies: [
                "CoreModels",
                "CoreNetworking",
                "FeatureAuthCore",
                "MediaTransportCore",
                "MediaTransportFTP",
                "MediaTransportHTTP",
                "MediaTransportNFS",
                "MediaTransportSFTP",
                "MediaTransportSMB",
                "MediaTransportWebDAV",
                "ProviderJellyfin",
                "ProviderPlex",
                "ProviderShare",
            ]
        ),

        // MARK: Shared media-share onboarding (used by both tvOS + iOS shells)
        .target(
            name: "FeatureShareOnboarding",
            dependencies: [
                "AppRuntime",
                "CoreModels",
                "CoreNetworking",
                "FeatureAuthCore",
                "ProviderShare",
                "MediaTransportHTTP",
                "MediaTransportWebDAV",
                "MediaTransportSFTP",
                "MediaTransportFTP",
                "MediaTransportNFS",
            ]
        ),

        // MARK: App composition root
        .target(
            name: "AppShell",
            dependencies: [
                "FeatureShareOnboarding",
                "AppRuntime",
                "CoreModels",
                "CoreNetworking",
                "CoreUI",
                "EnginePlozzigen",
                "FeatureDiscovery",
                "FeatureDiscoveryCore",
                "FeatureAuth",
                "FeatureHomeCore",
                "MediaTransportCore",
                "MediaTransportHTTP",
                "MediaTransportSMB",
                "MediaTransportWebDAV",
                "MediaTransportSFTP",
                "MediaTransportNFS",
                "MediaTransportFTP",
                "MediaDownloads",
                "MetadataKit",
                "ProviderJellyfin",
                "ProviderPlex",
                "ProviderShare",
                "ProviderTrailers",
                "RatingsService",
                "TraktService",
                "SeerService",
                "SimklService",
                "AniListService",
                "MALService",
                "LastFmService",
                "FeatureHome",
                "FeaturePlayback",
                "FeatureSearch",
                "FeatureSettings",
                "FeatureProfiles",
                "FeatureMusic",
                "FeatureSyncSetup",
                "TopShelfKit",
                "CrashReporting",
            ]
        ),
        .target(
            name: "AppShelliOS",
            dependencies: [
                "FeatureShareOnboarding",
                "AppRuntime",
                "CoreModels",
                "CoreNetworking",
                "CoreUI",
                "CrashReporting",
                "EnginePlozzigen",
                "FeatureAuthCore",
                "FeatureDiscoveryCore",
                "FeatureHomeCore",
                "HeroUI",
                "FeaturePlayback",
                "FeatureProfiles",
                "FeatureSearchCore",
                "MediaDownloads",
                "MediaTransportCore",
                "MediaTransportFTP",
                "MediaTransportHTTP",
                "MediaTransportNFS",
                "MediaTransportSFTP",
                "MediaTransportWebDAV",
                "ProviderPlex",
                "ProviderShare",
                "SeerService",
                "TraktService",
                "SimklService",
                "AniListService",
                "MALService",
                "FeatureSyncSetup",
            ]
        ),

        // MARK: Tests (pure logic, no UI required)
        .testTarget(
            name: "CoreModelsTests",
            dependencies: ["CoreModels", "CoreUI"]
        ),
        .testTarget(
            name: "FeatureSyncSetupTests",
            dependencies: ["FeatureSyncSetup", "CoreModels"]
        ),
        .testTarget(
            name: "AppRuntimeTests",
            dependencies: ["AppRuntime", "CoreModels", "FeatureAuthCore"]
        ),
        .testTarget(
            name: "MediaDownloadsTests",
            dependencies: ["MediaDownloads", "CoreModels", "MediaTransportCore"]
        ),
        .testTarget(
            name: "AppShellTests",
            dependencies: ["AppRuntime", "AppShell", "CoreModels", "FeatureHomeCore", "MediaTransportSFTP", "MediaTransportFTP", "MediaTransportNFS", "MediaTransportWebDAV"]
        ),
        .testTarget(
            name: "CoreUITests",
            dependencies: ["CoreUI", "CoreModels"]
        ),
        .testTarget(
            name: "CoreNetworkingTests",
            dependencies: ["CoreNetworking", "CoreModels"]
        ),
        .testTarget(
            name: "MetadataKitTests",
            dependencies: ["MetadataKit", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureDiscoveryTests",
            dependencies: ["FeatureDiscoveryCore", "CoreModels"]
        ),
        .testTarget(
            name: "ProviderJellyfinTests",
            dependencies: ["ProviderJellyfin", "ProviderPlex", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "ProviderPlexTests",
            dependencies: ["ProviderPlex", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "ProviderTrailersTests",
            dependencies: ["ProviderTrailers", "CoreModels"]
        ),
        .testTarget(
            name: "RatingsServiceTests",
            dependencies: ["RatingsService", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "TraktServiceTests",
            dependencies: ["TraktService", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "SeerServiceTests",
            dependencies: ["SeerService", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "FeatureAuthTests",
            dependencies: ["FeatureAuthCore", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureHomeTests",
            dependencies: [
                "FeatureHome",
                "FeatureHomeCore",
                "HeroUI",
                "CoreModels"
            ]
        ),
        .testTarget(
            name: "FeatureHomeCoreTests",
            dependencies: ["FeatureHomeCore", "CoreModels", "MetadataKit"]
        ),
        .testTarget(
            name: "FeatureSearchCoreTests",
            dependencies: ["FeatureSearchCore", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureProfilesTests",
            dependencies: ["FeatureProfiles", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureMusicTests",
            dependencies: ["FeatureMusic", "CoreModels"]
        ),
        .testTarget(
            name: "FeaturePlaybackTests",
            dependencies: ["FeaturePlayback", "CoreModels"]
        ),
        .testTarget(
            name: "ProviderShareTests",
            dependencies: ["ProviderShare", "CoreModels", "MediaTransportCore"]
        ),
        .testTarget(
            name: "FeatureSettingsTests",
            dependencies: ["FeatureSettings", "CoreModels"]
        ),
        .testTarget(
            name: "MediaTransportCoreTests",
            dependencies: ["MediaTransportCore", "CoreModels"],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportHTTPTests",
            dependencies: ["MediaTransportHTTP", "MediaTransportCore"],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportSMBTests",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportSMB",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportWebDAVTests",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportHTTP",
                "MediaTransportWebDAV",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportSFTPTests",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportSFTP",
                .product(name: "NIOSSH", package: "swift-nio-ssh"),
                .product(name: "NIOCore", package: "swift-nio"),
                .product(name: "NIOEmbedded", package: "swift-nio"),
                .product(name: "Crypto", package: "swift-crypto"),
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "TransportNFSTests",
            dependencies: ["TransportNFS"],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportNFSTests",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportNFS",
                "TransportNFS",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "MediaTransportFTPTests",
            dependencies: [
                "CoreModels",
                "MediaTransportCore",
                "MediaTransportFTP",
            ],
            swiftSettings: [.unsafeFlags(["-strict-concurrency=complete"])]
        ),
        .testTarget(
            name: "EnginePlozzigenTests",
            dependencies: [
                "CoreModels",
                "EnginePlozzigen",
                "MediaTransportCore",
                .product(name: "AetherEngine", package: "AetherEngine"),
            ]
        ),
    ],
    // Pin Swift 5 language mode: bumping tools-version to 6.0 (required for the
    // tvOS 18 `.tvOS(.v18)` platform) would otherwise default every module to
    // the Swift 6 language mode and its stricter concurrency migration. The app
    // target (project.yml) still builds SWIFT_VERSION 5.9; keep the SPM modules
    // in lockstep so behaviour is unchanged.
    swiftLanguageModes: [.v5]
)
