// swift-tools-version:5.9
import PackageDescription
import Foundation

// MARK: - Plozz modular package
//
// Plozz is split into small, single-responsibility modules so that:
//  * pure logic (models, networking, discovery, session) is unit-testable in
//    isolation, without a running tvOS UI;
//  * a second provider (Plex, Phase 2) can be dropped in behind `MediaProvider`
//    without touching feature code;
//  * build times stay low and ownership boundaries stay clear.
//
// The tvOS application target itself lives in `App/` and is generated by
// XcodeGen (see `project.yml`); it links the `AppShell` product below.
let package = Package(
    name: "Plozz",
    platforms: [
        .tvOS(.v17)
    ],
    products: [
        .library(name: "CoreModels", targets: ["CoreModels"]),
        .library(name: "CoreNetworking", targets: ["CoreNetworking"]),
        .library(name: "CoreUI", targets: ["CoreUI"]),
        .library(name: "MetadataKit", targets: ["MetadataKit"]),
        .library(name: "EngineMPV", targets: ["EngineMPV"]),
        .library(name: "FeatureDiscovery", targets: ["FeatureDiscovery"]),
        .library(name: "ProviderJellyfin", targets: ["ProviderJellyfin"]),
        .library(name: "ProviderPlex", targets: ["ProviderPlex"]),
        .library(name: "ProviderTrailers", targets: ["ProviderTrailers"]),
        .library(name: "RatingsService", targets: ["RatingsService"]),
        .library(name: "TraktService", targets: ["TraktService"]),
        .library(name: "SimklService", targets: ["SimklService"]),
        .library(name: "AniListService", targets: ["AniListService"]),
        .library(name: "MALService", targets: ["MALService"]),
        .library(name: "LastFmService", targets: ["LastFmService"]),
        .library(name: "FeatureAuth", targets: ["FeatureAuth"]),
        .library(name: "FeatureHome", targets: ["FeatureHome"]),
        .library(name: "FeaturePlayback", targets: ["FeaturePlayback"]),
        .library(name: "FeatureSearch", targets: ["FeatureSearch"]),
        .library(name: "FeatureSettings", targets: ["FeatureSettings"]),
        .library(name: "FeatureProfiles", targets: ["FeatureProfiles"]),
        .library(name: "FeatureMusic", targets: ["FeatureMusic"]),
        .library(name: "TopShelfKit", targets: ["TopShelfKit"]),
        .library(name: "CrashReporting", targets: ["CrashReporting"]),
        .library(name: "AppShell", targets: ["AppShell"])
    ],
    dependencies: [
        // Pure-Swift, dependency-free YouTube stream extractor. Backs online
        // trailer playback: TMDb hands us a YouTube video id, YouTubeKit resolves
        // a natively-playable progressive stream URL we feed straight to AVPlayer
        // (the same approach Infuse uses). It includes an optional remote fallback
        // so extraction keeps working when YouTube changes its internal API.
        .package(url: "https://github.com/alexeichhorn/YouTubeKit.git", from: "0.4.8"),

        // AetherEngine — production media player engine for Apple platforms.
        // FFmpeg demuxes, VideoToolbox decodes, AVPlayer handles Dolby Atmos.
        // Powers the native HLS-fMP4 remux path for MKV → DoVi + Atmos + seek.
        // 4.8.0: unified `playbackPhase` status source-of-truth (#85), keyframe-
        // gated VOD segment cutting so a seek landing on a segment boundary
        // decodes cleanly (#92), software-path seek holds last frame (#90). See
        // AGENTS.local.md › "Playback engine (AetherEngine / Plozzigen)".
        //
        // Pinned to the upstream merge commit for the backward-seek muxer wedge
        // fix (PR #94, merged into superuser404notfound/AetherEngine main as
        // 8e4ed87 — 4.8.0 plus the fix). Under +delay_moov the fMP4 muxer writes
        // moov lazily on the first flush; for AC-3/E-AC-3/TrueHD the audio sample
        // entry (dac3/dec3/dmlp) can only be built from a PARSED audio packet, so a
        // fresh restart muxer whose first moov flush fired video-only errored
        // "Cannot write moov atom before EAC3 packets parsed" → wedged muxer +
        // forever-loading on a mid-file backward seek. The fix primes moov with a
        // parsed audio packet, codec-scoped so AAC keeps the exact stock path. Bump
        // to the released upstream tag (`from:`) once one past 4.8.0 is cut.
        .package(url: "https://github.com/superuser404notfound/AetherEngine", revision: "8e4ed87c6a46a1e05164a1a556f942989eb8a7d0"),
        // AetherEngine's FFmpeg build (n8.1.2, minimal LGPL decode-only). Shared
        // by AetherEngine and EngineMPV — replaces the locally-staged
        // Frameworks/mpv/Libav*.xcframework set (same n8.1 ABI).
        .package(url: "https://github.com/superuser404notfound/FFmpegBuild", from: "1.0.1"),
        // Dolby Vision RPU parser/converter (prebuilt xcframework, no Rust at
        // build time). Used by AetherEngine for DV P7→8.1 NAL surgery; also
        // satisfies libmpv's dovi symbol references.
        .package(url: "https://github.com/superuser404notfound/LibDovi", from: "1.0.2"),

        // Sentry (getsentry/sentry-cocoa) — powers the OPT-IN, off-by-default
        // crash reporter (Settings ▸ Help & Diagnostics ▸ Share Crash Reports).
        // Prebuilt binary xcframework (no build-time compilation of the SDK).
        // Nothing is sent unless the user opts in AND a DSN was baked into the
        // build; see the `CrashReporting` target for the privacy-hardened config.
        .package(url: "https://github.com/getsentry/sentry-cocoa", from: "9.19.0"),
    ],
    targets: [
        // MARK: Core
        .target(name: "CoreModels"),
        .target(
            name: "CoreNetworking",
            dependencies: ["CoreModels"]
        ),

        // MARK: Shared UI (design system + reusable tvOS components)
        .target(
            name: "CoreUI",
            dependencies: ["CoreModels", "MetadataKit"]
        ),

        // MARK: Scalable external metadata/artwork (content-type-routed providers)
        //
        // Foundation-only so it stays unit-testable off-device. Houses the keyless,
        // per-IP artwork providers (AniList, Kitsu, TVmaze, Deezer, MusicBrainz),
        // the optional proxy/token-gated TMDb provider, the content-type classifier
        // + ArtworkRouter that picks the right provider chain, and a persistent
        // resolved-URL disk cache. This is the engine behind goals 1–5 scaling to
        // a large user base without a "bring your own API key" design.
        .target(
            name: "MetadataKit",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),

        // MARK: libmpv-backed engine (the on-device decoding path)
        //
        // Implements `MPVVideoEngine: VideoEngine` over libmpv (vo=gpu-next →
        // Vulkan → MoltenVK → Metal, hwdec=videotoolbox) for MKV/DTS/TrueHD/odd
        // codecs with libplacebo HDR tone-mapping. It depends on FeaturePlayback
        // purely to *see* the `VideoEngine` protocol (no cycle: FeaturePlayback
        // never imports it). This is the app's sole on-device decode engine for
        // AVPlayer-incompatible media — it replaced VLCKit, which is archived at
        // the `archive/vlckit-engine` git tag. A dedicated `EngineMPVProbe` tvOS
        // target (see project.yml) also links it as a compile/link gate.
        //
        // The FFmpeg + libmpv xcframeworks are LGPLv3 / decode-only (rebuilt by
        // tools/build-mpv-tvos.sh with `--disable-nonfree`, no `--enable-gpl`;
        // see NOTICE.md) and are referenced from local paths under
        // Frameworks/mpv/ (gitignored, staged by tools/stage-mpv-frameworks.sh).
        // The remaining prebuilt dependency xcframeworks are MPVKit's published,
        // checksummed binaries (license-unaffected by the FFmpeg config) pulled by
        // URL. Formal hosted/checksummed packaging of OUR FFmpeg/libmpv build is a
        // later step.
        .target(
            name: "EngineMPV",
            dependencies: [
                "CoreModels",
                "FeaturePlayback",
                // libmpv (local binary, LGPL-clean decode-only).
                "Libmpv",
                // FFmpeg libraries from the shared FFmpegBuild package (n8.1.x ABI).
                .product(name: "Libavcodec", package: "FFmpegBuild"),
                "Libavdevice",
                .product(name: "Libavfilter", package: "FFmpegBuild"),
                .product(name: "Libavformat", package: "FFmpegBuild"),
                .product(name: "Libavutil", package: "FFmpegBuild"),
                .product(name: "Libswresample", package: "FFmpegBuild"),
                .product(name: "Libswscale", package: "FFmpegBuild"),
                // libdovi from AetherEngine's LibDovi package.
                .product(name: "Dovi", package: "LibDovi"),
                // Prebuilt dependency xcframeworks (MPVKit-published, hosted).
                "Libssl", "Libcrypto", "Libass", "Libfreetype", "Libfribidi",
                "Libharfbuzz", "MoltenVK", "Libshaderc_combined", "lcms2",
                "Libplacebo", "Libunibreak", "gmp", "nettle",
                "hogweed", "gnutls",
                .product(name: "Libdav1d", package: "FFmpegBuild"),
                "Libuavs3d", "Libuchardet", "Libbluray"
            ],
            linkerSettings: [
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("CoreAudio"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CoreVideo"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("Metal"),
                .linkedFramework("VideoToolbox"),
                .linkedLibrary("bz2"),
                .linkedLibrary("iconv"),
                .linkedLibrary("expat"),
                .linkedLibrary("resolv"),
                .linkedLibrary("xml2"),
                .linkedLibrary("z"),
                .linkedLibrary("c++")
            ]
        ),

        // MARK: Providers
        .target(
            name: "ProviderJellyfin",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "ProviderPlex",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        // Synthetic provider for online (TMDb → YouTube) trailers. Conforms to
        // `MediaProvider` so a trailer can be played by the existing player; only
        // `playbackInfo(for:)` does real work (YouTubeKit stream extraction), the
        // rest are inert stubs. Kept in its own leaf module so YouTubeKit stays
        // out of every other target's link graph.
        .target(
            name: "ProviderTrailers",
            dependencies: [
                "CoreModels",
                .product(name: "YouTubeKit", package: "YouTubeKit")
            ]
        ),
        .target(
            name: "RatingsService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "TraktService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "SimklService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "AniListService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "MALService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "LastFmService",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),

        // MARK: Features
        .target(
            name: "FeatureDiscovery",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "FeatureAuth",
            dependencies: ["CoreModels", "CoreNetworking", "CoreUI", "ProviderJellyfin", "ProviderPlex"]
        ),
        .target(
            name: "FeatureHome",
            dependencies: ["CoreModels", "CoreNetworking", "CoreUI", "MetadataKit", "TopShelfKit", "RatingsService", "ProviderTrailers"]
        ),
        .target(
            name: "FeaturePlayback",
            dependencies: ["CoreModels", "CoreNetworking", "CoreUI", "TraktService", "MetadataKit"],
            linkerSettings: [
                // Force-link AVKit on tvOS so its `UIWindow (AVAdditions)`
                // category (which adds `avDisplayManager`, used to drive the
                // Dolby Vision / HDR display-mode switch) is registered at
                // runtime. Swift's autolink hint for a category-only reference
                // gets dropped through the SPM static-lib → app link, leaving the
                // selector unrecognized (instant crash) unless linked explicitly.
                .linkedFramework("AVKit", .when(platforms: [.tvOS]))
            ]
        ),
        .target(
            name: "FeatureSearch",
            dependencies: ["CoreModels", "CoreUI"]
        ),
        .target(
            name: "FeatureSettings",
            dependencies: ["CoreModels", "CoreUI", "FeatureProfiles", "TraktService", "SimklService", "AniListService", "MALService", "LastFmService"]
        ),
        .target(
            name: "FeatureProfiles",
            dependencies: ["CoreModels", "CoreUI"]
        ),

        // MARK: Music (browse + audio playback engine)
        //
        // Self-contained music experience: aggregator/view models, the conditional
        // Music tab UI, and the app-scoped `AudioPlaybackController` (AVQueuePlayer
        // + background audio + Now Playing). Depends only on CoreModels/CoreUI so
        // it stays decoupled from the video feature modules.
        .target(
            name: "FeatureMusic",
            dependencies: ["CoreModels", "CoreUI", "MetadataKit", "CoreNetworking"]
        ),

        // MARK: Top Shelf (shared with the tvOS Top Shelf extension)
        //
        // `TopShelfSnapshot` + `TopShelfStore` are Foundation-only and are also
        // compiled directly into the Top Shelf extension by source path (see
        // project.yml). `TopShelfPublisher` imports CoreModels and is therefore
        // app-only — the extension never compiles it.
        .target(
            name: "TopShelfKit",
            dependencies: ["CoreModels"]
        ),

        // MARK: Crash reporting (opt-in, off by default)
        //
        // Wraps Sentry behind a small `CrashReporter` protocol so the rest of the
        // app never imports Sentry directly and builds without a DSN are a true
        // no-op. Reports are only ever sent when the user has opted in (Settings ▸
        // Help & Diagnostics) AND the build shipped with a `PLOZZ_SENTRY_DSN`.
        // The Sentry config here is privacy-hardened: crash + hang captures only,
        // all automatic UI/network telemetry disabled, and a hard scrub of PII in
        // `beforeSend`/`beforeBreadcrumb`. Depends only on Sentry + Foundation.
        .target(
            name: "CrashReporting",
            dependencies: [
                .product(name: "Sentry", package: "sentry-cocoa"),
            ]
        ),

        // MARK: AetherEngine integration (native HLS-fMP4 remux engine)
        //
        // Wraps AetherEngine (the upstream media-player library) behind Plozz's
        // `VideoEngine` protocol. AetherEngine handles: FFmpeg demux → on-device
        // copy-remux → localhost HLS-fMP4 → AVPlayer, with bounded segment cache,
        // backpressure, producer-restart seek, Dolby Vision signaling, and Atmos
        // passthrough. This module is the integration adapter — all Plozz-specific
        // orchestration (server progress, subtitles, routing) stays in
        // FeaturePlayback / PlayerViewModel.
        .target(
            name: "EnginePlozzigen",
            dependencies: [
                "CoreModels",
                "FeaturePlayback",
                .product(name: "AetherEngine", package: "AetherEngine"),
            ]
        ),

        // MARK: App composition root
        .target(
            name: "AppShell",
            dependencies: [
                "CoreModels",
                "CoreNetworking",
                "CoreUI",
                "EngineMPV",
                "EnginePlozzigen",
                "FeatureDiscovery",
                "FeatureAuth",
                "MetadataKit",
                "ProviderJellyfin",
                "ProviderPlex",
                "ProviderTrailers",
                "RatingsService",
                "TraktService",
                "SimklService",
                "AniListService",
                "MALService",
                "LastFmService",
                "FeatureHome",
                "FeaturePlayback",
                "FeatureSearch",
                "FeatureSettings",
                "FeatureProfiles",
                "FeatureMusic",
                "TopShelfKit",
                "CrashReporting"
            ]
        ),

        // MARK: Tests (pure logic, no UI required)
        .testTarget(
            name: "CoreModelsTests",
            dependencies: ["CoreModels", "CoreUI"]
        ),
        .testTarget(
            name: "AppShellTests",
            dependencies: ["AppShell", "CoreModels"]
        ),
        .testTarget(
            name: "CoreUITests",
            dependencies: ["CoreUI", "CoreModels"]
        ),
        .testTarget(
            name: "CoreNetworkingTests",
            dependencies: ["CoreNetworking", "CoreModels"]
        ),
        .testTarget(
            name: "MetadataKitTests",
            dependencies: ["MetadataKit", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureDiscoveryTests",
            dependencies: ["FeatureDiscovery", "CoreModels"]
        ),
        .testTarget(
            name: "ProviderJellyfinTests",
            dependencies: ["ProviderJellyfin", "ProviderPlex", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "ProviderPlexTests",
            dependencies: ["ProviderPlex", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "ProviderTrailersTests",
            dependencies: ["ProviderTrailers", "CoreModels"]
        ),
        .testTarget(
            name: "RatingsServiceTests",
            dependencies: ["RatingsService", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "TraktServiceTests",
            dependencies: ["TraktService", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "FeatureAuthTests",
            dependencies: ["FeatureAuth", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureHomeTests",
            dependencies: ["FeatureHome", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureSearchTests",
            dependencies: ["FeatureSearch", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureProfilesTests",
            dependencies: ["FeatureProfiles", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureMusicTests",
            dependencies: ["FeatureMusic", "CoreModels"]
        ),
        .testTarget(
            name: "FeaturePlaybackTests",
            dependencies: ["FeaturePlayback", "CoreModels"]
        ),
        // EngineMPV tests require the Libmpv xcframeworks (staged by
        // tools/setup-mpv.sh) and compile only on tvOS. The test source is
        // guarded by `#if canImport(Libmpv) && canImport(UIKit)` so the target
        // builds to an empty test bundle in environments that lack those
        // frameworks (e.g. plain `swift build` on macOS).
        .testTarget(
            name: "EngineMPVTests",
            dependencies: ["EngineMPV", "CoreModels"]
        ),

        // MARK: - EngineMPV binary dependencies
        //
        // libmpv + Libavdevice are kept as local binary targets (not provided by
        // FFmpegBuild). All other FFmpeg libraries come from the shared FFmpegBuild
        // package. Staged under Frameworks/mpv/ (gitignored) by
        // tools/stage-mpv-frameworks.sh. NOT committed — regenerate locally before
        // building EngineMPV.
        .binaryTarget(name: "Libmpv", path: "Frameworks/mpv/Libmpv.xcframework"),
        .binaryTarget(name: "Libavdevice", path: "Frameworks/mpv/Libavdevice.xcframework"),

        // Prebuilt dependency xcframeworks — MPVKit's published, checksummed
        // binaries (independent libraries whose licenses are unaffected by the
        // FFmpeg config). Pulled by URL; pinned exactly as MPVKit 0.41.0-n8.1.
        .binaryTarget(
            name: "Libcrypto",
            url: "https://github.com/mpvkit/openssl-build/releases/download/3.3.5/Libcrypto.xcframework.zip",
            checksum: "593283be2a90f7fd66f6e6ed331b2f099cf403e0926fe3b4ac09a7062b793965"
        ),
        .binaryTarget(
            name: "Libssl",
            url: "https://github.com/mpvkit/openssl-build/releases/download/3.3.5/Libssl.xcframework.zip",
            checksum: "ff5ffd43d015d7285fd37e4a3145b25cbd8d2842740bd629a711c299a20e226a"
        ),
        .binaryTarget(
            name: "gmp",
            url: "https://github.com/mpvkit/gnutls-build/releases/download/3.8.11/gmp.xcframework.zip",
            checksum: "ad33c7a08f4cdcb9924c8f0e6d9a054dad33d7794b97667bf8b6fb2b236ae585"
        ),
        .binaryTarget(
            name: "nettle",
            url: "https://github.com/mpvkit/gnutls-build/releases/download/3.8.11/nettle.xcframework.zip",
            checksum: "0fdf3ebf8bd7b8bc8eee837cf27261cb4c52ae520b6576a2f468656aa1691e02"
        ),
        .binaryTarget(
            name: "hogweed",
            url: "https://github.com/mpvkit/gnutls-build/releases/download/3.8.11/hogweed.xcframework.zip",
            checksum: "25727c9fa67287fa0a4f4722f88bb8be669b23cd7e837e2d00870eb8a25d3f27"
        ),
        .binaryTarget(
            name: "gnutls",
            url: "https://github.com/mpvkit/gnutls-build/releases/download/3.8.11/gnutls.xcframework.zip",
            checksum: "3dbec5809339189bf9679e218c6cff387ebf8fb72745927835afc2678f5c9f4d"
        ),
        .binaryTarget(
            name: "Libunibreak",
            url: "https://github.com/mpvkit/libass-build/releases/download/0.17.4/Libunibreak.xcframework.zip",
            checksum: "001087c0e927ae00f604422b539898b81eb77230ea7700597b70393cd51e946c"
        ),
        .binaryTarget(
            name: "Libfreetype",
            url: "https://github.com/mpvkit/libass-build/releases/download/0.17.4/Libfreetype.xcframework.zip",
            checksum: "f2840aba1ce35e51c0595557eee82c908dac8e32108ecc0661301c06061e051c"
        ),
        .binaryTarget(
            name: "Libfribidi",
            url: "https://github.com/mpvkit/libass-build/releases/download/0.17.4/Libfribidi.xcframework.zip",
            checksum: "4a55513792ef7a17893875f74cc84c56f3657e8768c07a7a96f563a11dc4b743"
        ),
        .binaryTarget(
            name: "Libharfbuzz",
            url: "https://github.com/mpvkit/libass-build/releases/download/0.17.4/Libharfbuzz.xcframework.zip",
            checksum: "91558d8497d9d97bc11eeef8b744d104315893bfee8f17483d8002e14565f84b"
        ),
        .binaryTarget(
            name: "Libass",
            url: "https://github.com/mpvkit/libass-build/releases/download/0.17.4/Libass.xcframework.zip",
            checksum: "1e41f5a69c74f6c6407aab84a65ccd0b34e73fa44465f488f99bf22bd61b070d"
        ),
        .binaryTarget(
            name: "Libbluray",
            url: "https://github.com/mpvkit/libbluray-build/releases/download/1.4.0/Libbluray.xcframework.zip",
            checksum: "bc037d34e2b0b5ab7f202fb371f5fb298136cc66fdf406c2172185d06f53f18d"
        ),
        .binaryTarget(
            name: "Libuavs3d",
            url: "https://github.com/mpvkit/libuavs3d-build/releases/download/1.2.1-xcode/Libuavs3d.xcframework.zip",
            checksum: "1e69250279be9334cd2f6849abdc884c8e4bb29212467b6f071fdc1ac2010b6b"
        ),
        .binaryTarget(
            name: "MoltenVK",
            url: "https://github.com/mpvkit/moltenvk-build/releases/download/1.4.1/MoltenVK.xcframework.zip",
            checksum: "9bd1ca1e4563bacd25d6e55d37b10341d50b2601bc2684bc332188e79daa2b79"
        ),
        .binaryTarget(
            name: "Libshaderc_combined",
            url: "https://github.com/mpvkit/libshaderc-build/releases/download/2025.5.0/Libshaderc_combined.xcframework.zip",
            checksum: "758047b615708575b580eb960a2d083f760a29dc462d6eaa360416c946ce433b"
        ),
        .binaryTarget(
            name: "lcms2",
            url: "https://github.com/mpvkit/libplacebo-build/releases/download/7.349.0/lcms2.xcframework.zip",
            checksum: "bd2c27366f8b7adfe7bf652a922599891c55b82f5c519bcc4eece1ccff57c889"
        ),
        .binaryTarget(
            name: "Libplacebo",
            url: "https://github.com/mpvkit/libplacebo-build/releases/download/7.351.0-fix/Libplacebo.xcframework.zip",
            checksum: "99ca0b86e2a5a99c445d3e41df6f2fc08294e1a004b03f6a5645f299f06bf378"
        ),
        .binaryTarget(
            name: "Libuchardet",
            url: "https://github.com/mpvkit/libuchardet-build/releases/download/0.0.8-xcode/Libuchardet.xcframework.zip",
            checksum: "503202caa0dafb6996b2443f53408a713b49f6c2d4a26d7856fd6143513a50d7"
        )
    ]
)
