// swift-tools-version:5.9
import PackageDescription

// MARK: - Plizz modular package
//
// Plizz is split into small, single-responsibility modules so that:
//  * pure logic (models, networking, discovery, session) is unit-testable in
//    isolation, without a running tvOS UI;
//  * a second provider (Plex, Phase 2) can be dropped in behind `MediaProvider`
//    without touching feature code;
//  * build times stay low and ownership boundaries stay clear.
//
// The tvOS application target itself lives in `App/` and is generated by
// XcodeGen (see `project.yml`); it links the `AppShell` product below.
let package = Package(
    name: "Plizz",
    platforms: [
        .tvOS(.v17)
    ],
    products: [
        .library(name: "CoreModels", targets: ["CoreModels"]),
        .library(name: "CoreNetworking", targets: ["CoreNetworking"]),
        .library(name: "FeatureDiscovery", targets: ["FeatureDiscovery"]),
        .library(name: "ProviderJellyfin", targets: ["ProviderJellyfin"]),
        .library(name: "FeatureAuth", targets: ["FeatureAuth"]),
        .library(name: "FeatureHome", targets: ["FeatureHome"]),
        .library(name: "FeaturePlayback", targets: ["FeaturePlayback"]),
        .library(name: "FeatureSettings", targets: ["FeatureSettings"]),
        .library(name: "AppShell", targets: ["AppShell"])
    ],
    targets: [
        // MARK: Core
        .target(name: "CoreModels"),
        .target(
            name: "CoreNetworking",
            dependencies: ["CoreModels"]
        ),

        // MARK: Providers
        .target(
            name: "ProviderJellyfin",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),

        // MARK: Features
        .target(
            name: "FeatureDiscovery",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "FeatureAuth",
            dependencies: ["CoreModels", "CoreNetworking", "ProviderJellyfin"]
        ),
        .target(
            name: "FeatureHome",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "FeaturePlayback",
            dependencies: ["CoreModels", "CoreNetworking"]
        ),
        .target(
            name: "FeatureSettings",
            dependencies: ["CoreModels"]
        ),

        // MARK: App composition root
        .target(
            name: "AppShell",
            dependencies: [
                "CoreModels",
                "CoreNetworking",
                "FeatureDiscovery",
                "FeatureAuth",
                "ProviderJellyfin",
                "FeatureHome",
                "FeaturePlayback",
                "FeatureSettings"
            ]
        ),

        // MARK: Tests (pure logic, no UI required)
        .testTarget(
            name: "CoreModelsTests",
            dependencies: ["CoreModels"]
        ),
        .testTarget(
            name: "CoreNetworkingTests",
            dependencies: ["CoreNetworking", "CoreModels"]
        ),
        .testTarget(
            name: "FeatureDiscoveryTests",
            dependencies: ["FeatureDiscovery", "CoreModels"]
        ),
        .testTarget(
            name: "ProviderJellyfinTests",
            dependencies: ["ProviderJellyfin", "CoreModels", "CoreNetworking"]
        ),
        .testTarget(
            name: "FeatureAuthTests",
            dependencies: ["FeatureAuth", "CoreModels"]
        )
    ]
)
